### ISSUE TITLE
How to catch stop command?

### ISSUE THREAD

**Issue by mejmo** [snicoll-scratches/spring-boot-daemon#19] opened 2018-01-29 12:46 UTC
Is there any way how to catch stop command in `spring-boot-daemon-sample`? I need to gracefully stop the spring boot app and currently I think it is a force shutdown. Thanks

**Comment by snicoll** [comment] 2018-01-29 12:48
Duplicate of https://github.com/spring-projects/spring-boot/issues/4657

**Closed as completed by snicoll** 2018-01-29 12:48 UTC
